name: f_notification
description: Repeat Notification


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^15.1.1
  device_info_plus: ^9.0.3
  flutter_timezone: ^1.0.7
  http: ^1.1.0
  image: ^4.1.3
  path_provider: ^2.1.1
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - asstes/sound/notification_sound.mp3